apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: NodePort  # Change to LoadBalancer if using cloud
